spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http//config-server/bookkoo/auth-application # Config 서버 URI
      profile: default  # 사용할 프로파일
      label: main  # 사용할 Git 레이블 또는 브랜치