services:
  react-app:
    container_name: react-container
    build:
      context: ./frontend
    networks:
      - bookkoo-net
  auth-service:
    container_name: auth-service
    build:
      context: ./backend/auth-service
    ports:
      - "8085:8085"
    networks:
      - bookkoo-net
    restart: on-failure
    volumes:
      - ./logs/auth-service:/app/logs

  common-service:
    container_name: common-service
    build:
      context: ./backend/common-service
    ports:
      - "8086:8086"
      - "587:587"
    networks:
      - bookkoo-net
    restart: on-failure
    volumes:
      - ./logs/common-service:/app/logs

  eureka-server:
    container_name: eureka-server
    build:
      context: ./backend/eureka-server
    ports:
      - "8761:8761"
    networks:
      - bookkoo-net
    restart: on-failure

  book-service:
    container_name: book-service
    build:
      context: ./backend/book-service
    ports:
      - "8082:8082"
    networks:
      - bookkoo-net
    restart: on-failure
    volumes:
      - ./logs/book-service:/app/logs

  bookkoo-gateway:
    container_name: bookkoo-gateway
    build:
      context: ./backend/bookkoo-gateway
    ports:
      - "8080:8080"
    networks:
      - bookkoo-net
    restart: on-failure
    volumes:
      - ./logs/gateway-service:/app/logs

  curation-service:
    container_name: curation-service
    build:
      context: ./backend/curation-service
    ports:
      - "8084:8084"
    networks:
      - bookkoo-net
    restart: on-failure
    volumes:
      - ./logs/curation-service:/app/logs

  library-service:
    container_name: library-service
    build:
      context: ./backend/library-service
    ports:
      - "8083:8083"
    networks:
      - bookkoo-net
    restart: on-failure
    volumes:
      - ./logs/library-service:/app/logs

  member-service:
    container_name: member-service
    environment: 
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/bookkoo_google.json
    build:
      context: ./backend/member-service
    ports:
      - "8081:8081"
    networks:
      - bookkoo-net
    restart: on-failure
    volumes:
      - ./config/member-service:/app/config
      - ./logs/member-service:/app/logs
  
  booktalk-service:
    container_name: booktalk-service
    build:
      context: ./backend/booktalk-service
    ports:
      - "8087:8087"
    networks:
      - bookkoo-net
    restart: on-failure
    volumes:
      - ./logs/booktalk-service:/app/logs

  notification-service:
    container_name: notification-service
    build:
      context: ./backend/notification-service
    ports:
      - "8088:8088"
    networks:
      - bookkoo-net
    restart: on-failure
    volumes:
      - ./logs/notification-service:/app/logs

networks:
  bookkoo-net:
    driver: bridge
