services:
  auth-service:
    container_name: auth-service
    build:
      context: ./backend/auth-service
    networks:
      - npm_infra
    restart: on-failure
    volumes:
      - ./logs/auth-service:/app/logs

  common-service:
    container_name: common-service
    build:
      context: ./backend/common-service
    networks:
      - npm_infra
    restart: on-failure
    volumes:
      - ./logs/common-service:/app/logs

  eureka-server:
    container_name: eureka-server
    build:
      context: ./backend/eureka-server
    ports:
      - "8761:8761"
    networks:
      - npm_infra
    restart: on-failure

  book-service:
    container_name: book-service
    build:
      context: ./backend/book-service
    networks:
      - npm_infra
    restart: on-failure
    volumes:
      - ./logs/book-service:/app/logs

  bookkoo-gateway:
    container_name: bookkoo-gateway
    build:
      context: ./backend/bookkoo-gateway
    networks:
      - npm_infra
    restart: on-failure
    volumes:
      - ./logs/gateway-service:/app/logs

  curation-service:
    container_name: curation-service
    build:
      context: ./backend/curation-service
    networks:
      - npm_infra
    restart: on-failure
    volumes:
      - ./logs/curation-service:/app/logs

  library-service:
    container_name: library-service
    build:
      context: ./backend/library-service
    networks:
      - npm_infra
    restart: on-failure
    volumes:
      - ./logs/library-service:/app/logs

  member-service:
    container_name: member-service
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/bookkoo_google.json
    build:
      context: ./backend/member-service
    networks:
      - npm_infra
    restart: on-failure
    volumes:
      - ./config/member-service:/app/config
      - ./logs/member-service:/app/logs

  booktalk-service:
    container_name: booktalk-service
    build:
      context: ./backend/booktalk-service
    networks:
      - npm_infra
    restart: on-failure
    volumes:
      - ./logs/booktalk-service:/app/logs

  notification-service:
    container_name: notification-service
    build:
      context: ./backend/notification-service
    networks:
      - npm_infra
    restart: on-failure
    volumes:
      - ./logs/notification-service:/app/logs
