--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3 (Debian 16.3-1.pgdg120+1)
-- Dumped by pg_dump version 16.3 (Debian 16.3-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: book_talk; Type: TABLE; Schema: public; Owner: magumagu
--

CREATE TABLE public.book_talk (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    book bigint NOT NULL,
    day_message_count bigint,
    total_message_count bigint
);


ALTER TABLE public.book_talk OWNER TO magumagu;

--
-- Name: book_talk_id_seq; Type: SEQUENCE; Schema: public; Owner: magumagu
--

ALTER TABLE public.book_talk ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_talk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: book_talk_member_mapper; Type: TABLE; Schema: public; Owner: magumagu
--

CREATE TABLE public.book_talk_member_mapper (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    member_id bigint,
    booktalk bigint
);


ALTER TABLE public.book_talk_member_mapper OWNER TO magumagu;

--
-- Name: book_talk_member_mapper_id_seq; Type: SEQUENCE; Schema: public; Owner: magumagu
--

ALTER TABLE public.book_talk_member_mapper ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_talk_member_mapper_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: book_talk; Type: TABLE DATA; Schema: public; Owner: magumagu
--

COPY public.book_talk (id, created_at, updated_at, book, day_message_count, total_message_count) FROM stdin;
8	2024-08-15 05:19:53.963348	2024-08-15 05:19:53.963348	121	0	0
9	2024-08-15 06:34:38.720168	2024-08-15 06:34:55.897052	30	1	1
2	2024-08-13 07:36:53.308477	2024-08-15 12:14:01.332851	3	5	7
10	2024-08-15 17:51:43.831328	2024-08-15 17:51:49.341429	107	1	1
1	2024-08-13 07:29:56.012719	2024-08-15 22:46:19.812375	1	7	42
4	2024-08-14 13:20:05.261136	2024-08-14 13:20:10.476619	100	0	1
3	2024-08-13 07:37:56.59097	2024-08-14 14:38:18.603263	5	0	6
5	2024-08-14 16:18:42.994253	2024-08-14 16:18:42.994253	14	0	0
6	2024-08-15 05:12:37.276849	2024-08-15 05:12:37.276849	141	0	0
7	2024-08-15 05:13:01.712386	2024-08-15 05:13:01.712386	143	0	0
\.


--
-- Data for Name: book_talk_member_mapper; Type: TABLE DATA; Schema: public; Owner: magumagu
--

COPY public.book_talk_member_mapper (id, created_at, updated_at, member_id, booktalk) FROM stdin;
1	2024-08-13 07:29:56.497456	2024-08-13 07:29:56.497456	4	1
2	2024-08-13 07:30:04.672064	2024-08-13 07:30:04.672064	5	1
3	2024-08-13 07:36:08.935275	2024-08-13 07:36:08.935275	7	1
4	2024-08-13 07:36:17.612373	2024-08-13 07:36:17.612373	3	1
5	2024-08-13 07:36:53.507899	2024-08-13 07:36:53.507899	7	2
6	2024-08-13 07:37:56.96378	2024-08-13 07:37:56.96378	3	3
7	2024-08-13 08:16:02.444996	2024-08-13 08:16:02.444996	12	1
8	2024-08-13 08:16:13.703875	2024-08-13 08:16:13.703875	12	2
9	2024-08-13 08:16:16.130763	2024-08-13 08:16:16.130763	12	3
10	2024-08-14 00:08:46.610909	2024-08-14 00:08:46.610909	5	3
11	2024-08-14 00:51:08.557361	2024-08-14 00:51:08.557361	2	1
12	2024-08-14 03:30:50.635218	2024-08-14 03:30:50.635218	19	1
13	2024-08-14 04:54:56.060894	2024-08-14 04:54:56.060894	10	1
14	2024-08-14 05:06:01.524431	2024-08-14 05:06:01.524431	11	1
15	2024-08-14 07:38:31.516308	2024-08-14 07:38:31.516308	21	2
16	2024-08-14 09:45:47.990063	2024-08-14 09:45:47.990063	22	1
17	2024-08-14 13:03:57.082332	2024-08-14 13:03:57.082332	23	1
18	2024-08-14 13:04:35.737112	2024-08-14 13:04:35.737112	23	3
19	2024-08-14 13:17:45.840862	2024-08-14 13:17:45.840862	3	2
20	2024-08-14 13:20:05.485005	2024-08-14 13:20:05.485005	3	4
21	2024-08-14 14:37:49.265042	2024-08-14 14:37:49.265042	15	1
22	2024-08-14 14:38:15.537826	2024-08-14 14:38:15.537826	15	3
23	2024-08-14 16:18:43.183972	2024-08-14 16:18:43.183972	12	5
24	2024-08-15 04:19:54.453128	2024-08-15 04:19:54.453128	9	1
25	2024-08-15 05:06:46.649541	2024-08-15 05:06:46.649541	2	2
26	2024-08-15 05:07:44.868233	2024-08-15 05:07:44.868233	2	4
27	2024-08-15 05:07:50.060917	2024-08-15 05:07:50.060917	2	3
28	2024-08-15 05:08:00.281707	2024-08-15 05:08:00.281707	2	5
29	2024-08-15 05:12:37.416138	2024-08-15 05:12:37.416138	6	6
30	2024-08-15 05:13:01.808815	2024-08-15 05:13:01.808815	6	7
31	2024-08-15 05:15:09.915707	2024-08-15 05:15:09.915707	6	4
32	2024-08-15 05:15:12.214102	2024-08-15 05:15:12.214102	6	2
33	2024-08-15 05:15:17.725636	2024-08-15 05:15:17.725636	6	1
34	2024-08-15 05:15:26.970068	2024-08-15 05:15:26.970068	6	3
35	2024-08-15 05:16:01.479227	2024-08-15 05:16:01.479227	1	2
36	2024-08-15 05:17:18.116374	2024-08-15 05:17:18.116374	9	2
37	2024-08-15 05:19:56.304555	2024-08-15 05:19:56.304555	6	8
38	2024-08-15 06:34:38.86708	2024-08-15 06:34:38.86708	2	9
39	2024-08-15 08:35:16.140148	2024-08-15 08:35:16.140148	9	8
40	2024-08-15 08:40:41.451769	2024-08-15 08:40:41.451769	5	2
41	2024-08-15 08:40:43.484617	2024-08-15 08:40:43.484617	5	9
42	2024-08-15 08:40:45.507284	2024-08-15 08:40:45.507284	5	4
43	2024-08-15 10:58:29.864648	2024-08-15 10:58:29.864648	25	2
44	2024-08-15 12:13:41.726104	2024-08-15 12:13:41.726104	8	2
45	2024-08-15 17:44:48.167304	2024-08-15 17:44:48.167304	15	4
46	2024-08-15 17:44:52.464804	2024-08-15 17:44:52.464804	15	5
47	2024-08-15 17:51:44.160776	2024-08-15 17:51:44.160776	11	10
48	2024-08-15 17:53:49.564305	2024-08-15 17:53:49.564305	11	9
\.


--
-- Name: book_talk_id_seq; Type: SEQUENCE SET; Schema: public; Owner: magumagu
--

SELECT pg_catalog.setval('public.book_talk_id_seq', 10, true);


--
-- Name: book_talk_member_mapper_id_seq; Type: SEQUENCE SET; Schema: public; Owner: magumagu
--

SELECT pg_catalog.setval('public.book_talk_member_mapper_id_seq', 48, true);


--
-- Name: book_talk_member_mapper book_talk_member_mapper_pkey; Type: CONSTRAINT; Schema: public; Owner: magumagu
--

ALTER TABLE ONLY public.book_talk_member_mapper
    ADD CONSTRAINT book_talk_member_mapper_pkey PRIMARY KEY (id);


--
-- Name: book_talk book_talk_pkey; Type: CONSTRAINT; Schema: public; Owner: magumagu
--

ALTER TABLE ONLY public.book_talk
    ADD CONSTRAINT book_talk_pkey PRIMARY KEY (id);


--
-- Name: book_talk uk54vi63q8xryj8hee8anu1iupd; Type: CONSTRAINT; Schema: public; Owner: magumagu
--

ALTER TABLE ONLY public.book_talk
    ADD CONSTRAINT uk54vi63q8xryj8hee8anu1iupd UNIQUE (book);


--
-- Name: book_talk_member_mapper fkpv62i9ton3dsiw605rxp9hcmu; Type: FK CONSTRAINT; Schema: public; Owner: magumagu
--

ALTER TABLE ONLY public.book_talk_member_mapper
    ADD CONSTRAINT fkpv62i9ton3dsiw605rxp9hcmu FOREIGN KEY (booktalk) REFERENCES public.book_talk(id);


--
-- PostgreSQL database dump complete
--

