positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # push할 Loki의 주소

scrape_configs:
  - job_name: member
    static_configs:
      - targets:
          - localhost
        labels:
          job: member-service
          __path__: ./logs/member-service/*.log
  - job_name: book
    static_configs:
      - targets:
          - localhost
        labels:
          job: book-service
          __path__: ./logs/book-service/*.log
  - job_name: library
    static_configs:
      - targets:
          - localhost
        labels:
          job: library-service
          __path__: ./logs/library-service/*.log
  - job_name: curation
    static_configs:
      - targets:
          - localhost
        labels:
          job: curation-service
          __path__: ./logs/curation-service/*.log
  - job_name: common
    static_configs:
      - targets:
          - localhost
        labels:
          job: common-service
          __path__: ./logs/common-service/*.log
  - job_name: auth
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth-service
          __path__: ./logs/auth-service/*.log
  - job_name: gateway
    static_configs:
      - targets:
          - localhost
        labels:
          job: notification-service
          __path__: ./logs/notification-service/*.log
  - job_name: gateway
    static_configs:
      - targets:
          - localhost
        labels:
          job: gateway-service
          __path__: ./logs/gateway-service/*.log
