positions:
  filename: /tmp/positions.yaml 

clients:
  - url: http://loki:3100/loki/api/v1/push # push할 Loki의 주소

scrape_configs:
  - job_name: curation
    static_configs:
      - targets:
          - localhost
        labels:
          job: logs
          __path__: ./logs/curation-service/*.log 